#include <atomic>
#include <bitset>
#include <chrono>
#include <climits>
#include <csignal>
#include <cstring>
#include <fstream>
#include <functional>
#include <iostream>
#include <mutex>
#include <random>
#include <sstream>
#include <string>
#include <sys/wait.h>
#include <thread>
#include <unordered_map>
#include <unistd.h>
#include <vector>

#include "master.hpp"
#include "preprocessing.hpp"

using namespace std;

atomic<bool> running(true);
atomic<size_t> totalPatterns(0); // global state for total patterns output
mutex coutMutex;

string runLengthEncode(const string& str) {
    int n = str.size();
    string encoded;

    for (int i = 0; i < n; ++i) {
        int count = 1;
        while (i + 1 < n && str[i] == str[i + 1]) {
            ++count;
            ++i;
        }
        encoded += to_string(count) + str[i];
    }
    return encoded;
}


string translateFontFile(const string& chars, const vector<string>& masterDictionary) {
    vector<string> combinedRows;

    for (char c : chars) {
        if (c >= 32 && c <= 126) {
            const string& charData = masterDictionary[c - 32];
            istringstream stream(charData);
            string line;
            size_t rowIndex = 0;

            while (getline(stream, line)) {
                if (rowIndex >= combinedRows.size()) {
                    combinedRows.emplace_back();
                }
                combinedRows[rowIndex] += line;
                ++rowIndex;
            }
        } else {
            size_t charHeight = 16;
            size_t charWidth = 8;
            for (size_t rowIndex = 0; rowIndex < charHeight; ++rowIndex) {
                if (rowIndex >= combinedRows.size()) {
                    combinedRows.emplace_back();
                }
                combinedRows[rowIndex] += string(charWidth, '0');
            }
        }
    }

    ostringstream result;
    for (const auto& row : combinedRows) {
        result << row << '\n';
    }
    return result.str();
}

string conway_encode(const string& chars, const vector<string>& masterDictionary) {  // 99% of time
    string result = translateFontFile(chars, masterDictionary);                      // 52% of time

    // Pre-allocate exactly 16 rows
    vector<string> lines(16);
    int x_max = 0;
    int y_max = 0;

    istringstream stream(result);
    string line;

    // Process each line from the translated font data
    while (getline(stream, line) && y_max < 16) {  // Ensure `lines` never exceeds 16 rows
        if (!line.empty() && line.find('1') != string::npos) {
            x_max = max(x_max, static_cast<int>(line.size()));

            // Replace '0' → 'b' and '1' → 'o'
            for (char& ch : line) {
                ch = (ch == '0') ? 'b' : 'o';
            }

            // Store the encoded line in pre-allocated vector
            lines[y_max++] = runLengthEncode(line);  // 22% of time
        }
    }

    // Create the final RLE-formatted output
    ostringstream final_stream;
    // final_stream << "#C Generated by ASCII-to-Conway program\n";
    // final_stream << "#r 23/3\n";
    // final_stream << format("x = {}, y = {}\n", x_max, y_max);

    // Output encoded lines, separating rows with '$'
    for (int i = 0; i < y_max; ++i) {
        final_stream << lines[i];
        if (i < y_max - 1) {
            final_stream << "$";
        }
    }
    final_stream << "!";

    return final_stream.str();
}

const string CHARACTERS =
    " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~";

void generate_combination(size_t number, size_t length, const string& characters, string& out) {
    size_t base = characters.size();
    for (size_t i = 0; i < length; ++i) {
        out[length - i - 1] = characters[number % base];
        number /= base;
    }
}

bool next_combination(string& current, const string& characters) {
    for (size_t i = current.size(); i-- > 0;) {
        if (current[i] != characters.back()) {
            current[i] = characters[characters.find(current[i]) + 1];
            return true;
        }
        current[i] = characters.front();
    }
    return false; // Reached the final combination
}

void handle_signal(int signal) {
    if (signal == SIGINT) {
        running = false;
    }
}


#include <csignal>
#include <thread>

void workerFunction(size_t start, size_t end, const vector<string>& masterDictionary, size_t testLength, const string& characters, const vector<const char*>& apgluxeArgs, size_t id) {
    string currentPattern(testLength, characters.front());

    int pipefd[2];
    if (pipe(pipefd) == -1) {
        perror("pipe");
        return;
    }

    pid_t pid = fork();
    if (pid == -1) {
        perror("fork");
        return;
    }

    if (pid == 0) {  // Child process
        close(pipefd[1]);  // Close write end in the child
        dup2(pipefd[0], STDIN_FILENO);  // Redirect read end to stdin
        close(pipefd[0]);

        // Execute the apgluxe application
        execvp("./apgluxe", const_cast<char* const*>(apgluxeArgs.data()));
        perror("execvp");
        exit(EXIT_FAILURE);
    } else {  // Parent process
        close(pipefd[0]);  // Close read end in the parent

        for (size_t i = start; i < end && running; ++i) {
            generate_combination(i, testLength, characters, currentPattern);
            string encoded = conway_encode(currentPattern, masterDictionary);

            string output = "x=0,y=0,r=B3/S23\n" + encoded + '\n';

            // Add logs to check the output being sent
            {
                lock_guard<mutex> lock(coutMutex);
                //cout << "Thread " << id << " writing: " << output << endl;
            }

            if (write(pipefd[1], output.c_str(), output.size()) == -1) {
                perror("write");
                break;
            }
        }

        // Send the final game state after all combinations
        string finalGameState = "x=0,y=0,r=B3/S23\n3o!";
        if (write(pipefd[1], finalGameState.c_str(), finalGameState.size()) == -1) {
            perror("write");
        }

        close(pipefd[1]);  // Close the write end to signal EOF

        // Wait for child process to exit, or timeout after 10 seconds
        std::thread timeoutThread([pid]() {
            std::this_thread::sleep_for(std::chrono::seconds(999));
            if (kill(pid, 0) == 0) {
                kill(pid, SIGTERM);
                cerr << "Child process did not exit in time and was terminated." << endl;
            }
        });

        int status;
        waitpid(pid, &status, 0);

        if (timeoutThread.joinable()) {
            timeoutThread.join();
        }

        if (WIFEXITED(status)) {
            int exitStatus = WEXITSTATUS(status);
            if (exitStatus != 0) {
                cerr << "Child exited with status " << exitStatus << endl;
            }
        } else if (WIFSIGNALED(status)) {
            cerr << "Child process was terminated by signal " << WTERMSIG(status) << endl;
        }

        {
            lock_guard<mutex> lock(coutMutex);
            cout << "Thread " << id << " finished generating." << endl;
        }
    }
}

int main(int argc, char* argv[]) {
    size_t testLength = 2;  // Default value for test length
    int opt;

    if(argc <= 1){
        cerr << "Usage: " << argv[0] << " -l <testlength> -- <apgluxe arguments>" << endl;
        cerr << "Example: \n" << "./conway -l 5 -- -t 1 -n 99" << endl;
        return EXIT_FAILURE;
    }

    // Option parsing
    while ((opt = getopt(argc, argv, "l:")) != -1) {
        switch (opt) {
            case 'l':
                testLength = stoi(optarg);
                break;
            default:
                cerr << "Usage: " << argv[0] << " [-l testLength]" << endl;
                return EXIT_FAILURE;
        }
    }

    vector<const char*> apgluxeArgs = {"apgluxe"};

    // Add additional arguments after the `--`
    for (int i = optind; i < argc; ++i){
        apgluxeArgs.push_back(argv[i]);
    }
    apgluxeArgs.push_back(nullptr);

    // Verify and initialize masterDictionary before using
    //vector<string> masterDictionary; // assume it's initiated and populated correctly
    if (masterDictionary.empty()) {
        cerr << "Master dictionary is not initialized properly." << endl;
        return EXIT_FAILURE;
    }

    // Ensure apgluxe is executable
    if (access("./apgluxe", X_OK) == -1) {
        cerr << "apgluxe is not executable." << endl;
        return EXIT_FAILURE;
    }

    size_t threadCount = std::max(2U, std::thread::hardware_concurrency());
    vector<thread> workers;
    size_t totalCombinations = std::pow(CHARACTERS.size(), testLength);
    size_t chunkSize = totalCombinations / threadCount;

    // Launch threads with unique work chunks
    for (size_t i = 0; i < threadCount; ++i) {
        size_t start = i * chunkSize;
        size_t end = (i == threadCount - 1) ? totalCombinations : (i + 1) * chunkSize;
        workers.emplace_back(workerFunction, start, end, cref(masterDictionary), testLength, cref(CHARACTERS), cref(apgluxeArgs), i);
    }

    // Wait for all threads to complete
    for (auto& worker : workers) {
        if (worker.joinable()) {
            worker.join();
        }
    }

    return 0;
}